changed piping of stdout stream, fixed overflowing nohup.out

diff --git a/S54isoident b/S54isoident
--- a/S54isoident
+++ b/S54isoident
@@ -13,14 +13,18 @@ USER=root
 
 #ISOIDENT_OPTS=" -d ${DATASETS} -f ${CONF_FILE} -g ${CANLOGGER_CONFIG}"
 ISOIDENT_OPTS="-c can0 -d ${DATASETS} -f ${CONF_FILE}"
-SIGNAL = "SIGTERM"
+SIGNAL="TERM"
+PIPE=">/dev/null 2>/media/disk/isoident/isoident_err.log"
+
+if [ -r ${MMC} ]
+then
 
 case "$1" in
 start)
 	
 	echo -n "Starting ${NAME}:"
 	
-	if sudo nohup ${NAME} ${ISOIDENT_OPTS}& 2>/media/disk/isoident/isoident_err.log 1>/dev/null; then
+	if (sudo nohup ${NAME} ${ISOIDENT_OPTS} ${PIPE}&) ; then
 	echo "done"
 	else 
 	echo "failed"
@@ -33,7 +37,7 @@ stop)
 
 	echo -n "Stopping ${NAME}:"
 	
-	if  ${PKILL} -${SIGNAL} ${NAME}  ; then
+	if  sudo kill -${SIGNAL} ${NAME}  ; then
 	echo "done"
 	else 
 	echo "failed"
@@ -45,16 +49,15 @@ restart)
 
   /etc/init.d/S54isoident stop
   sleep 1
-  /etc/init.d/S53isoident start
+  /etc/init.d/S54isoident start
   
 	;;
 
 esac
-
   else
 
-    echo "missing sd card"
-    exit 1
-   fi
+    	echo "missing sd card"
+    	exit 1
+  fi
    
 exit 0
